"use client";

import { useEffect, useMemo, useState } from "react";

import { getInboxPackMode, type InboxPackMode } from "@/lib/api";
import {
  ACTION_CHECKLIST_CHANGED_EVENT,
  checklistProgress,
  hashSuggestion,
  isItemChecked,
  loadChecklistStore,
  saveChecklistStore,
  setItemChecked,
  type ChecklistStore,
} from "@/lib/action-checklist-storage";

type Props = {
  emailId: string;
  emailSubject: string;
  emailFrom: string;
  loginId: string;
  items: string[];
  deadlines?: string[];
};

export function ActionChecklist({
  emailId,
  emailSubject,
  emailFrom,
  loginId,
  items,
  deadlines,
}: Props) {
  const [pack, setPack] = useState<InboxPackMode>("live");
  const [store, setStore] = useState<ChecklistStore>({ emails: {}, updatedAt: 0 });
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const p = getInboxPackMode();
    setPack(p);
    setStore(loadChecklistStore(p, loginId));
    setHydrated(true);
  }, [loginId]);

  const progress = useMemo(
    () => checklistProgress(store, emailId, items),
    [store, emailId, items],
  );

  function toggle(text: string, nextChecked: boolean) {
    const key = hashSuggestion(text);
    const next = setItemChecked(store, emailId, key, nextChecked);
    setStore(next);
    saveChecklistStore(pack, loginId, next);
    window.dispatchEvent(new CustomEvent(ACTION_CHECKLIST_CHANGED_EVENT));
  }

  function exportPrint() {
    const win = window.open("", "_blank", "noopener,noreferrer,width=720,height=900");
    if (!win) return;
    const escape = (s: string) =>
      s.replace(/[&<>"']/g, (c) =>
        ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string),
      );
    const today = new Date().toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
    const dl = (deadlines ?? []).filter(Boolean);
    const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>Action checklist · ${escape(emailSubject)}</title>
<style>
  body{font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:#202124;margin:32px;}
  h1{font-size:18px;margin:0 0 4px;}
  .meta{color:#5f6368;font-size:12px;margin-bottom:16px;}
  .pill{display:inline-block;border:1px solid #fde293;background:#fef7e0;color:#7a4d00;
        border-radius:999px;padding:1px 8px;font-size:11px;font-weight:600;margin-right:6px;}
  ul{padding-left:0;list-style:none;}
  li{margin:8px 0;display:flex;gap:8px;align-items:flex-start;}
  .box{display:inline-block;width:14px;height:14px;border:1.5px solid #5f6368;border-radius:3px;
       margin-top:2px;flex:none;}
  .box.checked{background:#137333;border-color:#137333;position:relative;}
  .box.checked::after{content:"";position:absolute;left:3px;top:0;width:4px;height:8px;
       border:solid #fff;border-width:0 2px 2px 0;transform:rotate(45deg);}
  .footer{margin-top:24px;color:#80868b;font-size:11px;}
  @media print{button{display:none;}}
</style></head>
<body>
  <h1>${escape(emailSubject || "Opportunity")}</h1>
  <div class="meta">From ${escape(emailFrom || "—")} · Generated ${escape(today)}</div>
  ${dl.length ? `<div>${dl.map((d) => `<span class="pill">Deadline ${escape(d)}</span>`).join("")}</div>` : ""}
  <ul>
    ${items
      .map((t) => {
        const checked = isItemChecked(store, emailId, hashSuggestion(t));
        return `<li><span class="box ${checked ? "checked" : ""}"></span><span>${escape(t)}</span></li>`;
      })
      .join("")}
  </ul>
  <div class="footer">Generated by Opportunity Inbox Copilot — SOFTEC 2026</div>
  <button type="button" onclick="window.print()" style="margin-top:18px;padding:6px 14px;font-size:13px;
    border:1px solid #dadce0;background:#0b57d0;color:white;border-radius:6px;cursor:pointer;">
    Print this checklist
  </button>
</body></html>`;
    win.document.open();
    win.document.write(html);
    win.document.close();
  }

  if (items.length === 0) return null;

  return (
    <div className="mt-3 rounded-xl border border-[#c4e0ff] bg-[#f0f7ff] px-3 py-2.5">
      <div className="flex items-center justify-between gap-2">
        <span className="text-[10px] font-semibold uppercase tracking-wide text-[#174ea6]">
          Action checklist
        </span>
        <div className="flex items-center gap-2">
          {hydrated ? (
            <span className="text-[11px] font-semibold text-[#174ea6]">
              {progress.done}/{progress.total} done
            </span>
          ) : null}
          <button
            type="button"
            onClick={exportPrint}
            className="rounded-md border border-[#c4e0ff] bg-white px-2 py-0.5 text-[11px] font-semibold text-[#0b57d0] hover:bg-[#e8f0fe]"
          >
            Print / Export
          </button>
        </div>
      </div>
      {hydrated ? (
        <div className="mt-1.5 h-1 w-full overflow-hidden rounded-full bg-[#dbe7fb]">
          <div
            className="h-full rounded-full bg-[#0b57d0] transition-[width] duration-200"
            style={{ width: `${Math.round(progress.pct * 100)}%` }}
          />
        </div>
      ) : null}
      <ul className="mt-2 space-y-1.5">
        {items.map((t, i) => {
          const key = hashSuggestion(t);
          const checked = hydrated && isItemChecked(store, emailId, key);
          return (
            <li key={`${i}-${key}`} className="flex items-start gap-2 text-[12px] leading-snug">
              <input
                type="checkbox"
                aria-label={t}
                checked={checked}
                onChange={(e) => toggle(t, e.target.checked)}
                className="mt-[3px] h-3.5 w-3.5 cursor-pointer accent-[#0b57d0]"
              />
              <span className={checked ? "text-[#5f6368] line-through" : "text-[#1f1f1f]"}>{t}</span>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
